name: Alpha builds

on:
  workflow_dispatch:

jobs:
  build-data:
    name: Generate build data
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.data.outputs.dotversion }}
      sha: ${{ steps.data.outputs.shortsha }}
      build_date: ${{ steps.data.outputs.builddate }}
      rust_version: '1.51.0' # update this every so often to match latest stable rust release
    steps:
      - uses: actions/checkout@v2

      - name: Export release data
        id: data
        shell: bash
        run: |
          echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"
          echo "::set-output name=builddate::$(date +"%Y-%m-%d")"

  linux:
    runs-on: ubuntu-latest
    needs: [build-data]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup git
        run: |
          git config --global user.email "trickypr@users.noreply.github.com"
          git config --global user.name "TrickyPR"

      - name: Install system dependancies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get update
          sudo apt-get install dos2unix yasm nasm build-essential libgtk2.0-dev libpython3-dev m4 uuid libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdrm-dev libdbus-glib-1-dev libdbus-glib-1-dev libgtk-3-dev libpulse-dev libx11-xcb-dev libxt-dev xvfb ldd llvm
          pip install pycairo testresources

      - name: Install WASI SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-14/wasi-sdk_14.0_amd64.deb
          sudo apt install ./wasi-sdk_14.0_amd64.deb

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install sccache
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: 0.2.13
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Save sccache
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: /home/runner/.cache/sccache
          key: ${{ runner.os }}-sccache-${{ needs.build-data.outputs.shortsha }}
          restore-keys: |
            ${{ runner.os }}-sccache-

      - name: Get System Info
        run: |
          llc --version

      - name: Setup melon
        run: yarn && yarn setupLink

      - name: Download firefox source and dependancies
        run: yarn download

      - name: Import
        run: yarn imp

      - name: Bootstrap
        run: |
          cd engine
          ./mach --no-interactive bootstrap --application-choice browser
          cd ..

      - name: Build
        run: yarn build

      - name: Package
        run: yarn melon package

      - name: Rename artifacts
        run: |
          cp ./engine/obj-*/dist/focus-browser-*.tar.bz2 .
          mv focus-browser-*.tar.bz2 "focus-browser.linux.tar.bz2"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: focus-browser.linux.tar.bz2
          path: ./focus-browser.linux.tar.bz2

  flatpak:
    name: 📦 Flatpak
    needs: [build-data, linux]
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged

    steps:
      - name: Clone packaging scripts
        run: git clone --recurse-submodules https://github.com/focus-browser/packages.git

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/download-artifact@v2
        with:
          name: focus-browser.linux.tar.bz2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Save flatpak cache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: ./packages/flatpak/.flatpak-builder/cache
          key: ${{ runner.os }}-flatpak-${{ needs.build-data.outputs.shortsha }}
          restore-keys: |
            ${{ runner.os }}-flatpak-

      - name: Download binaries
        run: |
          cd packages/flatpak
          cp ../../focus-browser.linux.tar.bz2 ./focus-browser.tar.bz2
          tar -xvf focus-browser.tar.bz2
      - uses: bilelmoussaoui/flatpak-github-actions@v2
        with:
          bundle: focus-browser.linux.flatpak
          manifest-path: './packages/flatpak/com.fushra.browser.desktop.yml'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: focus-browser.linux.flatpak
          path: ./focus-browser.linux.flatpak

      - name: Build for Alpha repo
        run: |
          export deploy_acc_key=$TRICKYPR_TOKEN
          cd packages/flatpak
          chmod +x ./build.sh
          ./build.sh
