name: Alpha builds

on:
  push:
    branches: [alpha]
  pull_request:
    branches: [alpha]

  workflow_dispatch:

jobs:
  build-data:
    name: 🧬 Generate build data
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.data.outputs.dotversion }}
      sha: ${{ steps.data.outputs.shortsha }}
      build_date: ${{ steps.data.outputs.builddate }}
      rust_version: '1.51.0' # update this every so often to match latest stable rust release
    steps:
      - uses: actions/checkout@v2

      - name: Export release data
        id: data
        shell: bash
        run: |
          echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"
          echo "::set-output name=builddate::$(date +"%Y-%m-%d")"

  linux:
    runs-on: ubuntu-latest
    needs: [build-data]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install system dependancies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get update
          sudo apt-get install dos2unix yasm nasm build-essential libgtk2.0-dev libpython3-dev m4 uuid libasound2-dev libcurl4-openssl-dev libdbus-1-dev libdrm-dev libdbus-glib-1-dev libdbus-glib-1-dev libgtk-3-dev libpulse-dev libx11-xcb-dev libxt-dev xvfb

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install sccache
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: 0.2.13
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Save sccache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: /home/runner/.cache/sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sccache-

      - name: Setup melon
        run: yarn && yarn setupLink

      - name: Download firefox source and dependancies
        run: yarn download

      - name: Import
        run: yarn imp

      - name: Bootstrap
        run: |
          cd engine
          ./mach --no-interactive bootstrap --application-choice browser
          cd ..

      - name: Build
        run: yarn build

      - name: Rename artifacts
        run: |
          cp ./engine/obj-*/dist/focus-browser-*.tar.bz2 .
          mv dot-*.tar.bz2 "focus-browser.linux.tar.bz2"

      - name: Package
        run: yarn melon package

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ needs.build-data.outputs.build_date }}-${{ needs.build-data.outputs.shortsha }}'
          prerelease: true
          title: 'Alpha build'
          files: |
            focus-browser.linux.tar.bz2
