name: CI and tests

on:
  workflow_dispatch:
  push:
    branches: [alpha, beta]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [alpha, beta]

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Melon
        run: yarn && yarn setupLink

      - name: Check license
        run: yarn licenseCheck --no-fix
